_USERNAME = 'tuck'
_DATA_LOC = '/home/' + _USERNAME + '/Datasets/vgg_face_dataset/'
LINK_LOC = _DATA_LOC + 'files/'
RECORD_LOC = _DATA_LOC + 'records/'
TEST_RECORD_LOC = _DATA_LOC + 'test_records/'
PEOPLE_LOC = _DATA_LOC + 'people/'
TEST_PEOPLE_LOC = _DATA_LOC + 'test_people/'
CHECKPOINT_LOC = 'saves/'
FACE_SIZE = (32, 32)
EMBEDDING_SIZE = 128